PREFIX spatial: <http://jena.apache.org/spatial#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

SELECT
	?latitude
	?longitude
	?name
	{{dataPointDescriptionSelect}}

{{from}}

WHERE {

	?mapPoint	spatial:withinBox ( {{minLat}} {{minLong}} {{maxLat}} {{maxLong}} {{spatialLimit}}) ;
				{{addressPath}} ?address ;
    			{{latitudePath}} ?lat ;
    			{{longitudePath}} ?long .

	?dataPoint	a {{dataPointType}} ;
				{{dataPointName}} ?name ;
				{{mapPointPath}} ?mapPoint .

	BIND (xsd:float(?lat) AS ?latitude) .
	BIND (xsd:float(?long) AS ?longitude) .

	{{dataPointDescriptionOptional}}
}
